routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home')->name('home');
Route::get('contact', 'PageController@contact')->name('contact');

Route::prefix('blog')->group(function () {
    Route::get('/', 'BlogController@index')->name('blog.index');
    Route::get('/category/{id}/{slug?}', 'BlogController@category')->name('blog.category');
    Route::get('/archive/{year}/{month}', 'BlogController@archive')->name('blog.archive');
    Route::get('/post/{id}/{slug?}', 'BlogController@post')->name('blog.post');
});

/*Route::prefix('stories')->group( function() {
    Route::get('/', 'StoriesController@index')->name('stories.index');
    Route::get('/genre/{id}/{slug?}', 'StoriesController@genre')->name('stories.genre');
    Route::get('/book/{story_id}/{chapter_id}/{story_slug?}/{chapter_slug?}',
        'StoriesController@book')->name('stories.book');
});*/

/*Route::get('/kitchen_sink', function () {
    return view('layout.kitchen_sink');
});*/

Route::prefix('admin')
    ->namespace('Admin')
    ->middleware('auth')
    ->group(function () {
        Route::get('/', 'AdminPageController@index');
        Route::resource('category', 'CategoryController', ['except' => ['show']]);
        Route::resource('post', 'PostController');
        Route::resource('genre', 'GenreController', ['except' => ['show']]);
        Route::resource('label', 'LabelController', ['except' => ['show']]);
        Route::resource('story', 'StoryController');
        Route::prefix('story/{story}')->group(function () {
            Route::resource('chapter', 'ChapterController');
            Route::resource('note', 'AuthorNoteController');
        });

        Route::get('/logout', 'AdminPageController@logout')->name('admin.logout');
});

Route::prefix('apiv1')
    ->namespace('API')
    ->group(function () {
        Route::get('twitch', 'TwitchController@index')->name('twitch');
    });

Auth::routes();

resources/views/layout/admin.blade.php
@include('layout.head')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav class="nav">
                <a class="nav-link" href="{{ route('post.index') }}">Posts</a>
                <a class="nav-link" href="{{ route('category.index') }}">Categories</a>
                <a class="nav-link" href="{{ route('story.index') }}">Stories</a>
                <a class="nav-link" href="{{ route('genre.index') }}">Genres</a>
                <a class="nav-link" href="{{ route('label.index') }}">Content Labels</a>
                <a class="nav-link disabled" href="#">Users</a>
                <a class="nav-link" href="{{ route('admin.logout') }}">Log Out</a>
            </nav>
        </div>
    </div>
        <h1 class="text-center">{{ $title or 'PAGE TITLE NEEDED' }}</h1>
        @yield('content')
</div>
@include('layout.footer')

resources/views/layout/default.blade.php
@include('layout.head')
@yield('content')
@include('layout.footer')

resources/views/layout/footer.blade.php
<hr>
<footer class="py-5">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; {{ $copyrightYear }} Bachman I/O</p>
    </div>
</footer>



<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
<script defer src="{{ env('CDN_URL') }}/js/app.js"></script>
<script src="https://embed.twitch.tv/embed/v1.js"></script>
<script defer type="text/javascript">
    $(document).ready(function() {
        response = null;
        $.ajax(
            {
                url: '{{ route('twitch') }}',
                data: response,
                dataType: 'json'
            }
        ).done(function(response) {
            if(response.data.length !== 0) {
                $('#twitchTitle').text(response.data[0].title);
                $('#twitchCard').show();
            }
        });
    });
</script>
</body>
</html>

resources/views/layout/head.blade.php
<!doctype html>
<html lang="en" prefix="
og: http://ogp.me/ns#">
<head>

    <title>{{ isset($title) ? $title . ' - Bachman I/O'  : 'Bachman I/O' }}</title>
    <meta name="author" content="Collin Bachman">
    <meta name="description" content="{{ isset($description) ? $description : 'No description available' }}">

    @if( isset($post) && Route::currentRouteName('blog.post'))
        <meta property="og:title" content="{{ $post->title }}" />
        <meta property="og:type" content="article" />
        <meta property="og:url" content="{{ url()->current() }}" />
        @if (!is_null($post->title_bg_image_url))
        <meta property="og:image" content="{{ $post->title_bg_image_url }}" />
        @endif
        <meta property="og:description" content="{{ $post->lead_text }}" />
        <meta property="og:site_name" content="Bachman I/O" />
        <meta name="twitter:card" content="summary_large_image" />
    @endif

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel=apple-touch-icon" sizes="180x180" href="{{ env('CDN_URL') }}/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ env('CDN_URL') }}/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ env('CDN_URL') }}/favicon-16x16.png">
    <link rel="manifest" href="{{ env('CDN_URL') }}/site.webmanifest">
    <link rel="mask-icon" href="{{ env('CDN_URL') }}/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#135ba0">


    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Bootstrap core CSS -->
    <link href="{{ env('CDN_URL') }}/css/app.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.8.0/spectrum.min.css">


</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background: #666;">
    <div class="container">
        <div class="links mx-auto">
            <a href="{{ route('home') }}">
                <img src="{{ env('CDN_URL') }}/bachman-io-logo.svg" width="270" height="30" alt="Bachman I/O">
            </a>
        </div>
        {{--
    <div class="collapse navbar-collapse" id="mainNav">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item">
                <a class="nav-link" href="{{ route('home') }}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('blog.index') }}">Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('stories.index') }}">Stories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('contact') }}">Contact</a>
            </li>
        </ul>

    </div>
    --}}
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="card mb-4" id="twitchCard" style="display: none;">
            <h5 class="card-header text-center">We're Live on Twitch!</h5>
            <div class="card-body">
                <h1 id="twitchTitle"></h1>
                <a href="#" target="_blank" class="btn btn-primary btn-lg">Go to Twitch &rarr;</a>
            </div>
        </div>
    </div>
</div>