routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home')->name('home');
Route::get('contact', 'PageController@contact')->name('contact');

Route::prefix('blog')->group(function () {
    Route::get('/', 'BlogController@index')->name('blog.index');
    Route::get('/category/{id}/{slug?}', 'BlogController@category')->name('blog.category');
    Route::get('/archive/{year}/{month}', 'BlogController@archive')->name('blog.archive');
    Route::get('/post/{id}/{slug?}', 'BlogController@post')->name('blog.post');
});

/*Route::prefix('stories')->group( function() {
    Route::get('/', 'StoriesController@index')->name('stories.index');
    Route::get('/genre/{id}/{slug?}', 'StoriesController@genre')->name('stories.genre');
    Route::get('/book/{story_id}/{chapter_id}/{story_slug?}/{chapter_slug?}',
        'StoriesController@book')->name('stories.book');
});*/

/*Route::get('/kitchen_sink', function () {
    return view('layout.kitchen_sink');
});*/

Route::prefix('admin')
    ->namespace('Admin')
    ->middleware('auth')
    ->group(function () {
        Route::get('/', 'AdminPageController@index');
        Route::resource('category', 'CategoryController', ['except' => ['show']]);
        Route::resource('post', 'PostController');
        Route::resource('genre', 'GenreController', ['except' => ['show']]);
        Route::resource('label', 'LabelController', ['except' => ['show']]);
        Route::resource('story', 'StoryController');
        Route::prefix('story/{story}')->group(function () {
            Route::resource('chapter', 'ChapterController');
            Route::resource('note', 'AuthorNoteController');
        });

        Route::get('/logout', 'AdminPageController@logout')->name('admin.logout');
});

Route::prefix('apiv1')
    ->namespace('API')
    ->group(function () {
        Route::get('twitch', 'TwitchController@index')->name('twitch');
    });

Auth::routes();

app/Genre.php
<?php

namespace App;

use App\Http\Requests\StoreGenre;
use Illuminate\Database\Eloquent\Model;

class Genre extends Model
{

    /**
     * Fillable fields when mass-assigning the Model
     *
     * @var array
     */
    protected $fillable = ['name', 'slug'];

    /**
     * Returns collection of stories with this genre
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function stories()
    {
        return $this->hasMany('App\Story');
    }

    /**
     * Genres in alphabetical order, or null if none
     *
     * @return mixed
     */
    public function alphabetic()
    {
        return $this->orderBy('name')->get();
    }

    /**
     * Genre names and story counts for sidebar,
     * or null if none
     *
     * @return mixed
     */
    public function genreLinks()
    {
        return $this->whereHas('stories', function ($q) {
            $q->where('published', true);
        })->withCount(['stories' => function ($q) {
            $q->where('published', true);
        }])->orderBy('name')->get();
    }

    /**
     * List of genre's stories, or null if none
     *
     * @param $id
     * @return mixed
     */
    public function genreList($id)
    {
        return $this->find($id)->stories()
            ->where('published', 1)
            ->whereHas('chapters')
            ->withCount([
                'chapters as published_chapters' => function ($query) {
                    $query->where('published', true);
                }
            ])
            ->orderBy('created_at', 'desc')
            ->paginate(10);
    }

    /**
     * Add a new genre
     *
     * @param StoreGenre $request
     */
    public function addNew(StoreGenre $request)
    {
        $this->name = $request->name;
        $this->slug = $request->slug;
        $this->save();
    }

    /**
     * Update an existing genre
     *
     * @param $id
     * @param StoreGenre $request
     */
    public function updateExisting($id, StoreGenre $request)
    {
        $genre = $this->find($id);
        $genre->name = $request->name;
        $genre->slug = $request->slug;
        $genre->save();
    }
}

app/Http/Controllers/Admin/GenreController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\StoreGenre;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Genre;

class GenreController extends Controller
{

    private $genre;

    public function __construct(Genre $genre)
    {
        $this->genre = $genre;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->data['title'] = 'Genres';
        $this->data['genres'] = $this->genre->all();
        return view('admin.genre.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['title'] = 'New Genre';
        return view('admin.genre.new', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreGenre $request)
    {
        $this->genre->addNew($request);
        return redirect()->route('genre.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  integer $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  integer $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->data['title'] = 'Edit Genre';
        $this->data['genre'] = $this->genre->findOrFail($id);
        return view('admin.genre.edit', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  integer                  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreGenre $request, $id)
    {
        $this->genre->updateExisting($id, $request);
        return redirect()->route('genre.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  integer $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/genre/edit.blade.php
@extends('layout.admin')
@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('genre.update', $genre->id) }}" method="post">
        <input name="_method" type="hidden" value="PUT">
        @csrf
        <div class="row">
            <div class="col">
                <label for="name">Genre Name</label>
                <input name="name" id="name" type="text" class="form-control" value="{{ $genre->name }}" />
            </div>
            <div class="col">
                <label for="slug">Genre URL Slug</label>
                <input name="slug" id="slug" type="text" class="form-control" value="{{ $genre->slug }}" />
            </div>
        </div>
        <div class="row">
            <div class="col">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection

resources/views/admin/genre/index.blade.php
@extends('layout.admin')
@section('content')
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Slug</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @forelse($genres as $genre)
            <tr>
                <td>{{ $genre->id }}</td>
                <td>{{ $genre->name }}</td>
                <td>{{ $genre->slug }}</td>
                <td><a href="{{ route('genre.edit', $genre->id) }}">Edit</a></td>
            </tr>
        @empty
            <tr>
                <td colspan="4">There are no genres to display!</td>
            </tr>
        @endforelse
        </tbody>
    </table>
    <a href="{{ route('genre.create') }}" class="btn btn-primary">New Genre</a>
@endsection

resources/views/admin/genre/new.blade.php
@extends('layout.admin')
@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('genre.store') }}" method="post">
        @csrf
        <div class="row">
            <div class="col">
                <label for="name">Genre Name</label>
                <input name="name" id="name" type="text" class="form-control" placeholder="e.g. Fruits" />
            </div>
            <div class="col">
                <label for="slug">Genre URL Slug</label>
                <input name="slug" id="slug" type="text" class="form-control" placeholder="e.g. fruits" />
            </div>
        </div>
        <div class="row">
            <div class="col">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection