routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home')->name('home');
Route::get('contact', 'PageController@contact')->name('contact');

Route::prefix('blog')->group(function () {
    Route::get('/', 'BlogController@index')->name('blog.index');
    Route::get('/category/{id}/{slug?}', 'BlogController@category')->name('blog.category');
    Route::get('/archive/{year}/{month}', 'BlogController@archive')->name('blog.archive');
    Route::get('/post/{id}/{slug?}', 'BlogController@post')->name('blog.post');
});

/*Route::prefix('stories')->group( function() {
    Route::get('/', 'StoriesController@index')->name('stories.index');
    Route::get('/genre/{id}/{slug?}', 'StoriesController@genre')->name('stories.genre');
    Route::get('/book/{story_id}/{chapter_id}/{story_slug?}/{chapter_slug?}',
        'StoriesController@book')->name('stories.book');
});*/

/*Route::get('/kitchen_sink', function () {
    return view('layout.kitchen_sink');
});*/

Route::prefix('admin')
    ->namespace('Admin')
    ->middleware('auth')
    ->group(function () {
        Route::get('/', 'AdminPageController@index');
        Route::resource('category', 'CategoryController', ['except' => ['show']]);
        Route::resource('post', 'PostController');
        Route::resource('genre', 'GenreController', ['except' => ['show']]);
        Route::resource('label', 'LabelController', ['except' => ['show']]);
        Route::resource('story', 'StoryController');
        Route::prefix('story/{story}')->group(function () {
            Route::resource('chapter', 'ChapterController');
            Route::resource('note', 'AuthorNoteController');
        });

        Route::get('/logout', 'AdminPageController@logout')->name('admin.logout');
});

Route::prefix('apiv1')
    ->namespace('API')
    ->group(function () {
        Route::get('twitch', 'TwitchController@index')->name('twitch');
    });

Auth::routes();

app/Post.php
<?php

namespace App;

use App\Http\Requests\StorePost;
use Illuminate\Database\Eloquent\Model;

use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class Post extends Model
{

    protected $fillable = ['title',
        'slug',
        'published',
        'nsfw',
        'title_color',
        'title_bg_color',
        'title_bg_image_url',
        'author_id',
        'lead_text',
        'main_text'];

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function author()
    {
        return $this->belongsTo('App\User');
    }

    public function addNew(StorePost $request)
    {
        $this->title = $request->title;
        $this->slug = $request->slug;
        $this->type = $request->type;
        if (isset($request->published)) {
            $this->published = $request->published;
        }
        if (isset($request->nsfw)) {
            $this->nsfw = $request->nsfw;
        }
        $this->title_bg_image_url = $request->title_bg_image_url;
        $this->author_id = $request->author_id;
        $this->category_id = $request->category_id;
        $this->lead_text = $request->lead_text;
        $this->main_text = $request->main_text;
        $this->save();
    }

    public function updateExisting($id, StorePost $request)
    {
        $post = $this->findOrFail($id);
        $post->title = $request->title;
        $post->slug = $request->slug;
        $post->type = $request->type;
        if (isset($request->published)) {
            if ($post->published === 0) {
                $post->created_at = Carbon::now();
            }
            $post->published = $request->published;
        } else {
            $post->published = 0;
        }
        if (isset($request->nsfw)) {
            $post->nsfw = $request->nsfw;
        } else {
            $post->nsfw = 0;
        }
        $post->title_bg_image_url = $request->title_bg_image_url;
        $post->author_id = $request->author_id;
        $post->category_id = $request->category_id;
        $post->lead_text = $request->lead_text;
        $post->main_text = $request->main_text;
        $post->save();
    }

    public function latestOne()
    {
        return $this->where('published', 1)->orderBy('created_at', 'desc')
            ->first();
    }

    public function latestList($data)
    {
        $data['posts'] = $this->where('published', 1)->orderBy('created_at', 'desc')
            ->paginate(10);

        return $data;
    }

    public function allList($data)
    {
        $data['posts'] = $this->orderBy('created_at', 'desc')
            ->paginate(10);

        return $data;
    }

    public function categoryList($id)
    {
        $posts = $this->where([
            ['category_id', '=', $id],
            ['published', '=', 1]])
            ->orderBy('created_at', 'desc')
            ->paginate(10);

        return $posts;
    }

    public static function archiveLinks($data)
    {
        $data['archive_years'] = DB::table('posts')->select(
            DB::raw('YEAR(created_at) year')
        )
            ->where('published', 1)
            ->groupBy('year')
            ->orderBy('year', 'desc')
            ->distinct()
            ->get();
        $data['archive_months'] = [];
        if (!empty($data['archive_years'])) {
            foreach ($data['archive_years'] as $y) {
                $data['archive_months'][$y->year] = DB::table('posts')
                    ->select(DB::raw('MONTH(created_at) month,
                    MONTHNAME(created_at) month_name,
                    COUNT(*) posts_count'))
                    ->where([
                        [DB::raw('YEAR(created_at)'), '=', $y->year],
                        ['published', '=', 1]
                    ])
                    ->groupBy(['month', 'month_name'])
                    ->orderBy('month', 'desc')
                    ->distinct()
                    ->get();
            }
        }

        return $data;
    }

    public function handleSinglePostDates($post)
    {
        $postDates['created'] = $post->created_at->diffForHumans();
        $postDates['updated'] = $post->updated_at->diffForHumans();

        if ($post->created_at->diffInDays() >= 7) {
            $postDates['created'] = $post->created_at->format('F jS');
        }
        if (Carbon::now()->format('Y') > $post->created_at->format('Y')) {
            $postDates['created'] = $post->created_at->format('n/j/Y');
        }

        if ($post->updated_at->diffInDays() >= 7) {
            $postDates['updated'] = $post->updated_at->format('F jS');
        }
        if (Carbon::now()->format('Y') > $post->updated_at->format('Y')) {
            $postDates['updated'] = $post->updated_at->format('n/j/Y');
        }


        return $postDates;
    }

    public function findByDate($year, $month)
    {
        return $this->where([
            [DB::raw('YEAR(created_at)'), '=', $year],
            [DB::raw('MONTH(created_at)'), '=', $month],
            ['published', '=', 1]
        ])->orderBy('created_at', 'desc')
            ->paginate(10);
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Requests\StorePost;
use App\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PostController extends Controller
{

    private $post;
    private $category;

    public function __construct(Post $post, Category $category)
    {
        $this->post = $post;
        $this->category = $category;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Post $post
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->data['title'] = 'Posts';
        $this->data = $this->post->allList($this->data);
        return view('admin.post.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['title'] = 'New Post';
        $this->data['categories'] = $this->category->alphabetic();
        return view('admin.post.new', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StorePost $request
     * @param Post      $post
     * @return \Illuminate\Http\Response
     */
    public function store(StorePost $request)
    {
        $this->post->addNew($request);
        return redirect()->route('post.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  integer $id
     * @param Post    $post
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->data['post'] = $this->post->findOrFail($id);
        $this->data['postDate'] = $this->post->handleSinglePostDate($this->data['post']);
        $this->data['markdown']['main'] = $this->convertMarkdown($this->data['post']->main_text);
        $this->data['title'] = $this->data['post']->title;
        return view('blog.post', $this->data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  integer $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->data['title'] = 'Edit Post';
        $this->data['post'] = $this->post->findOrFail($id);
        $this->data['categories'] = $this->category->alphabetic();
        return view('admin.post.edit', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  integer                  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StorePost $request, $id)
    {
        $this->post->updateExisting($id, $request);
        return redirect()->route('post.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  integer $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/post/edit.blade.php
@extends('layout.admin')
@section('content')
    <div class="container">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form action="{{ route('post.update', $post->id) }}" method="post">
            <input name="_method" type="hidden" value="PUT">
            @csrf
            <div class="row">
                <div class="col">
                    <label for="title">Title</label>
                    <input name="title" id="title" type="text" class="form-control" value="{{ $post->title }}" />
                </div>
                <div class="col">
                    <label for="slug">Post URL Slug</label>
                    <input name="slug" id="slug" type="text" class="form-control" value="{{ $post->slug }}" />
                </div>
                <div class="col">
                    <label for="type">Post Type</label>
                    <select name="type" id="type" class="form-control">
                        <option {{ $post->type === 'Short' ? 'selected' : '' }} value="Short">Short</option>
                        <option {{ $post->type === 'Long' ? 'selected' : '' }} value="Long">Long</option>
                        <option {{ $post->type === 'Embed' ? 'selected' : '' }} value="Embed">Embed</option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <label for="author_name">Author</label>
                    <input type="text" readonly class="form-control-plaintext" id="author_name" value="{{ $post->author->name }}" />
                    <input type="hidden" name="author_id" value="{{ $post->author->id }}" />
                </div>
                <div class="col">
                    <label for="category_id">Category</label>
                    <select name="category_id" id="category_id" class="form-control">
                        @forelse($categories as $category)
                            <option
                                    @if($category->id === $post->category->id)
                                    selected
                                    @endif
                                    value="{{ $category->id }}">{{ $category->name }}</option>
                        @empty
                            <option selected>--No Categories Available--</option>
                        @endforelse
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <label for="title_bg_image_url">Title BG Image URL</label>
                    <input name="title_bg_image_url" id="title_bg_image_url" type="text" class="form-control" value="{{ $post->title_bg_image_url }}" />
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <label for="lead_text">Lead Text</label>
                    <textarea name="lead_text" id="lead_text" class="form-control" rows="5">{{ $post->lead_text }}
                </textarea>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <label for="main_text">Main Text</label>
                    <textarea name="main_text" id="main_text" class="form-control" rows="25">{{ $post->main_text }}</textarea>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div class="form-check">
                        <input name="published" class="form-check-input" type="checkbox" value="1" id="publishCheck" @if($post->published === 1) checked @endif>
                        <label class="form-check-label" for="publishCheck">
                            Publish this post?
                        </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-check">
                        <input name="nsfw" class="form-check-input" type="checkbox" value="1" id="nsfwCheck" @if($post->nsfw === 1) checked @endif>
                        <label class="form-check-label" for="nsfwCheck">
                            Not Safe for Work?
                        </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/admin/post/index.blade.php
@extends('layout.admin')
@section('content')
    <a href="{{ route('post.create') }}" class="btn btn-primary">New Post</a>
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Title</th>
            <th scope="col">Type</th>
            <th scope="col">Published?</th>
            <th scope="col">NSFW?</th>
            <th scope="col">Created</th>
            <th scope="col">Updated</th>
            <th scope="col">Author</th>
            <th scope="col">Category</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @forelse($posts as $post)
            <tr>
                <td>{{ $post->id }}</td>
                <td>{{ $post->title }}</td>
                <td>{{ $post->type }}</td>
                <td>
                    @if($post->published === 1)
                        Y
                    @else
                        N
                    @endif
                </td>
                <td>
                    @if($post->nsfw === 1)
                        Y
                    @else
                        N
                    @endif
                </td>
                <td>{{ $post->created_at->diffForHumans() }}</td>
                <td>{{ $post->updated_at->diffForHumans() }}</td>
                <td>{{ $post->author->name }}</td>
                <td>{{ $post->category->name }}</td>
                <td><a href="{{ route('post.show', $post->id) }}" target="_blank">Preview</a> <a href="{{ route('post.edit', $post->id) }}">Edit</a></td>
            </tr>
        @empty
            <tr>
                <td colspan="6">There are no posts to display!</td>
            </tr>
        @endforelse
        </tbody>
    </table>
    {{ $posts->links() }} <br>
@endsection

resources/views/admin/post/new.blade.php
@extends('layout.admin')
@section('content')
    <div class="container">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

            <form action="{{ route('post.store') }}" method="post">
                @csrf
                <div class="row">
                    <div class="col">
                        <label for="title">Title</label>
                        <input name="title" id="title" type="text" class="form-control" placeholder="e.g. Fruits" />
                    </div>
                    <div class="col">
                        <label for="slug">Post URL Slug</label>
                        <input name="slug" id="slug" type="text" class="form-control" placeholder="e.g. fruits" />
                    </div>
                    <div class="col">
                        <label for="type">Post Type</label>
                        <select name="type" id="type" class="form-control">
                            <option selected value="Short">Short</option>
                            <option value="Long">Long</option>
                            <option value="Embed">Embed</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <label for="author_name">Author</label>
                        <input type="text" readonly class="form-control-plaintext" id="author_name" value="{{ Auth::user()->name }}" />
                        <input type="hidden" name="author_id" value="{{ Auth::user()->id }}" />
                    </div>
                    <div class="col">
                        <label for="category_id">Category</label>
                        <select name="category_id" id="category_id" class="form-control">
                            @forelse($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @empty
                                <option selected>--No Categories Available--</option>
                            @endforelse
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <label for="title_bg_image_url">Title BG Image URL</label>
                        <input name="title_bg_image_url" id="title_bg_image_url" type="text" class="form-control" placeholder="http://www.example.com/image.png" />
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <label for="lead_text">Lead Text</label>
                        <textarea name="lead_text" id="lead_text" class="form-control" rows="5"></textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <label for="main_text">Main Text</label>
                        <textarea name="main_text" id="main_text" class="form-control" rows="25"></textarea>
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        <div class="form-check">
                            <input name="published" class="form-check-input" type="checkbox" value="1" id="publishCheck">
                            <label class="form-check-label" for="publishCheck">
                                Publish this post?
                            </label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="form-check">
                            <input name="nsfw" class="form-check-input" type="checkbox" value="1" id="nsfwCheck">
                            <label class="form-check-label" for="nsfwCheck">
                                Not Safe for Work?
                            </label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
    </div>
@endsection