routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home')->name('home');
Route::get('contact', 'PageController@contact')->name('contact');

Route::prefix('blog')->group(function () {
    Route::get('/', 'BlogController@index')->name('blog.index');
    Route::get('/category/{id}/{slug?}', 'BlogController@category')->name('blog.category');
    Route::get('/archive/{year}/{month}', 'BlogController@archive')->name('blog.archive');
    Route::get('/post/{id}/{slug?}', 'BlogController@post')->name('blog.post');
});

/*Route::prefix('stories')->group( function() {
    Route::get('/', 'StoriesController@index')->name('stories.index');
    Route::get('/genre/{id}/{slug?}', 'StoriesController@genre')->name('stories.genre');
    Route::get('/book/{story_id}/{chapter_id}/{story_slug?}/{chapter_slug?}',
        'StoriesController@book')->name('stories.book');
});*/

/*Route::get('/kitchen_sink', function () {
    return view('layout.kitchen_sink');
});*/

Route::prefix('admin')
    ->namespace('Admin')
    ->middleware('auth')
    ->group(function () {
        Route::get('/', 'AdminPageController@index');
        Route::resource('category', 'CategoryController', ['except' => ['show']]);
        Route::resource('post', 'PostController');
        Route::resource('genre', 'GenreController', ['except' => ['show']]);
        Route::resource('label', 'LabelController', ['except' => ['show']]);
        Route::resource('story', 'StoryController');
        Route::prefix('story/{story}')->group(function () {
            Route::resource('chapter', 'ChapterController');
            Route::resource('note', 'AuthorNoteController');
        });

        Route::get('/logout', 'AdminPageController@logout')->name('admin.logout');
});

Route::prefix('apiv1')
    ->namespace('API')
    ->group(function () {
        Route::get('twitch', 'TwitchController@index')->name('twitch');
    });

Auth::routes();

app/Label.php
<?php

namespace App;

use App\Http\Requests\StoreLabel;
use Illuminate\Database\Eloquent\Model;

class Label extends Model
{
    protected $fillable = ['name'];

    public function stories()
    {
        return $this->belongsToMany('App\Story');
    }

    public function alphabetic()
    {
        return $this->orderBy('name')->get();
    }

    public function addNew(StoreLabel $request)
    {
        $this->name = $request->name;
        $this->slug = $request->slug;
        $this->save();
    }

    public function updateExisting($id, StoreLabel $request)
    {
        $label = $this->find($id);
        $label->name = $request->name;
        $label->slug = $request->slug;
        $label->save();
    }
}

app/Http/Controllers/Admin/LabelController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\StoreLabel;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Label;

class LabelController extends Controller
{

    private $label;

    public function __construct(Label $label)
    {
        $this->label = $label;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->data['title'] = 'Content Labels';
        $this->data['labels'] = $this->label->all();
        return view('admin.label.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->data['title'] = 'New Content Label';
        return view('admin.label.new', $this->data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreLabel $request)
    {
        $this->label->addNew($request);
        return redirect()->route('label.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  integer $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  integer $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->data['title'] = 'Edit Content Label';
        $this->data['label'] = $this->label->findOrFail($id);
        return view('admin.label.edit', $this->data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  integer                  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreLabel $request, $id)
    {
        $this->label->updateExisting($id, $request);
        return redirect()->route('label.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  integer $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/label/edit.blade.php
@extends('layout.admin')
@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('label.update', $label->id) }}" method="post">
        <input name="_method" type="hidden" value="PUT">
        @csrf
        <div class="row">
            <div class="col">
                <label for="name">Content Label Name</label>
                <input name="name" id="name" type="text" class="form-control" value="{{ $label->name }}" />
            </div>
            <div class="col">
                <label for="slug">Content Label URL Slug</label>
                <input name="slug" id="slug" type="text" class="form-control" value="{{ $label->slug }}" />
            </div>
        </div>
        <div class="row">
            <div class="col">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection

resources/views/admin/label/index.blade.php
@extends('layout.admin')
@section('content')
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Slug</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @forelse($labels as $label)
            <tr>
                <td>{{ $label->id }}</td>
                <td>{{ $label->name }}</td>
                <td>{{ $label->slug }}</td>
                <td><a href="{{ route('label.edit', $label->id) }}">Edit</a></td>
            </tr>
        @empty
            <tr>
                <td colspan="4">There are no content labels to display!</td>
            </tr>
        @endforelse
        </tbody>
    </table>
    <a href="{{ route('label.create') }}" class="btn btn-primary">New Content Label</a>
@endsection

resources/views/admin/label/new.blade.php
@extends('layout.admin')
@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('label.store') }}" method="post">
        @csrf
        <div class="row">
            <div class="col">
                <label for="name">Content Label Name</label>
                <input name="name" id="name" type="text" class="form-control" placeholder="e.g. Fruits" />
            </div>
            <div class="col">
                <label for="slug">Content Label URL Slug</label>
                <input name="slug" id="slug" type="text" class="form-control" placeholder="e.g. fruits" />
            </div>
        </div>
        <div class="row">
            <div class="col">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection